# -*- coding: utf-8 -*-
"""254329031_sahin_inanc_ozkaya.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XVyYdc0whLsJoDPrFGt3sNLm-4dC86WH

# Veri Ön İşleme ve Keşifçi Analiz (EDA)

##Veri Çerçevesi Oluşturma
"""

import pandas as pd

# 1. CSV dosyasını okuyarak DataFrame oluşturma
# Dosya yolunu Colab'e yüklediğin dosya adıyla aynı olduğundan emin ol
df = pd.read_csv('real_drug_dataset.csv')

# 2. Veri çerçevesinin başarıyla oluşturulduğunu kontrol etme
print(f"DataFrame Oluşturuldu! Boyutlar: {df.shape}")
print("-" * 30)

# 3. İlk 5 satırı görüntüleme
display(df.head())

"""#Veri Seti Kalite Kontrolleri
## Eksik Değer Analizi
"""

import seaborn as sns

# --- 1. SAYISAL ANALİZ ---
print("1. Sayısal Eksik Değer Tablosu:")
eksik_sayisi = df.isnull().sum()
eksik_yuzdesi = (df.isnull().sum() / len(df)) * 100

eksik_tablosu = pd.concat([eksik_sayisi, eksik_yuzdesi], axis=1, keys=['Eksik Sayısı', 'Eksik Oranı (%)'])

# Sadece eksik değeri olanları filtrele
if eksik_tablosu['Eksik Sayısı'].sum() == 0:
    print("\nVeri setinde hiç eksik (NaN) değer bulunmamaktadır.")
else:
    display(eksik_tablosu[eksik_tablosu['Eksik Sayısı'] > 0])

"""##Aykırı Değer (Outlier) Analizi"""

# Sayısal sütunları seç
sayisal_sutunlar = ['Age', 'Dosage_mg', 'Treatment_Duration_days', 'Improvement_Score']

print("--- Aykırı Değer Analizi Sonuçları (IQR Yöntemi) ---\n")

for col in sayisal_sutunlar:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    alt_sinir = Q1 - 1.5 * IQR
    ust_sinir = Q3 + 1.5 * IQR

    aykiri_sayisi = ((df[col] < alt_sinir) | (df[col] > ust_sinir)).sum()

    if aykiri_sayisi > 0:
        print(f"⚠️ {col}: {aykiri_sayisi} adet aykırı değer bulundu.")
        print(f"   (Alt Sınır: {alt_sinir:.2f}, Üst Sınır: {ust_sinir:.2f})")
    else:
        print(f"✅ {col}: Temiz (Aykırı değer yok).")

"""Veri setimiz %99 oranında aykırı değerlerden arınmış, temiz bir yapıdadır. Sadece İyileşme Skoru değişkeninde tespit edilen %0.70 oranındaki aykırı değerler, 'tedavi başarısızlığı' olarak değerlendirilebilecek gerçek veriler olduğu için analizden çıkarılmamış, veri setinde tutulmuştur.

##Veri Tipi ve Dağılım İncelemesi
"""

veri_tipleri = df.dtypes
tip_sayilari = veri_tipleri.value_counts()

# --- 2. GÖRSELLEŞTİRME (BAR CHART) ---
plt.figure(figsize=(10, 6))

ax = sns.barplot(x=tip_sayilari.index.astype(str),
                 y=tip_sayilari.values,
                 hue=tip_sayilari.index.astype(str),
                 legend=False,
                 palette='viridis')

# Başlık ve Eksen İsimleri
plt.title('Veri Setindeki Değişken Tiplerinin Dağılımı', fontsize=14, fontweight='bold')
plt.xlabel('Veri Tipi (Dtype)', fontsize=12)
plt.ylabel('Değişken Sayısı', fontsize=12)

# Çubukların üzerine sayıları yazdırma
for p in ax.patches:
    ax.annotate(f'{int(p.get_height())}',
                (p.get_x() + p.get_width() / 2., p.get_height()),
                ha='center', va='center',
                fontsize=12, color='black',
                xytext=(0, 8),
                textcoords='offset points')

plt.ylim(0, max(tip_sayilari.values) + 1)
plt.show()

"""Veri seti yapısal olarak 5 adet kategorik (object) ve 4 adet sayısal (int64/float64) değişkenden oluşmaktadır.

Kategorik Değişkenler: İlaç adı, yan etkiler ve hastalık türü gibi metin tabanlı veriler çoğunluktadır; bu da veri setinin sınıflandırma (classification) analizleri için zengin bir içeriğe sahip olduğunu gösterir.

Sayısal Değişkenler: Yaş, dozaj ve iyileşme skoru gibi ölçülebilir değerler, istatistiksel analizler için yeterli nicel altyapıyı sağlamaktadır. Genel olarak veri seti, nitel ve nicel veri tipleri açısından dengeli bir yapı sergilemektedir.

#1. Tüm sayısal sütunlar için temel istatistikleri hesaplama (mean, std, min, %25, median, %75 ve max)
"""

# Veriyi yükleme
df = pd.read_csv('real_drug_dataset.csv')

# Sayısal sütunları seçme
sayisal_sutunlar = df.select_dtypes(include=['float64', 'int64'])

# İstenen istatistikleri hesaplama ve transpoze etme (Ters çevirme)
istatistikler = sayisal_sutunlar.describe().loc[['mean', 'std', 'min', '25%', '50%', '75%', 'max']].T

# Sütun isimlerini düzenleme
istatistikler.columns = ['Ortalama (Mean)', 'Std Sapma', 'Min', '%25 (Q1)', 'Medyan (%50)', '%75 (Q3)', 'Max']

# Sonucu gösterme
display(istatistikler)

"""#2. Kategorik sütunlardaki verileri her sütun için ayrı ayrı olacak şekilde pie chart (pasta grafiği) ile görselleştirme"""

import matplotlib.pyplot as plt

# ID sütunu her satırda benzersiz olduğu için pasta grafiği çizilmez.
kategorik_sutunlar = ['Gender', 'Condition', 'Drug_Name', 'Side_Effects']

for col in kategorik_sutunlar:
    # Veri sayımı
    veri = df[col].value_counts()

    # Grafik Çizimi
    plt.figure(figsize=(10, 10))
    plt.pie(veri,
            labels=veri.index,
            autopct='%1.1f%%',
            startangle=140,
            shadow=True) # Hafif gölge ekler, daha şık durur

    plt.title(f'{col} Dağılımı', fontsize=14, fontweight='bold')
    plt.show()

"""#3. Condition sütunu hastalık sebebini içermektedir. Bu sebeplere karşılık gelen tedavi süresi (Treatment_Duration_days) dağılımını tek bir boxplot üzerinde görselleştirilmesi"""

plt.figure(figsize=(15, 9))

sns.boxplot(x='Condition',
            y='Treatment_Duration_days',
            hue='Condition',
            legend=False,
            data=df,
            palette='Set2')

plt.title('Hastalık Sebebine Göre Tedavi Süreleri', fontsize=14, fontweight='bold')
plt.xlabel('Hastalık Sebebi')
plt.ylabel('Tedavi Süresi (Gün)')
plt.xticks(rotation=45)
plt.grid(axis='y', linestyle='--', alpha=0.7)

plt.show()

"""#4. Drug_Name ve Side_Effects sütunları için 2 boyutlu histogram (veya uygun bir 2D frekans görselleştirmesi) çizdirilmesi ve sonuçları yorumlanması"""

# 1. Çapraz Tablo (Crosstab) Oluşturma
# Bu işlem, her İlaç-Yan Etki çiftinin kaç kez geçtiğini sayar (Frekans Matrisi)
frekans_tablosu = pd.crosstab(df['Drug_Name'], df['Side_Effects'])

# 2. Görselleştirme (Heatmap)
plt.figure(figsize=(22, 10))

sns.heatmap(frekans_tablosu,
            annot=True,      # Kutucukların içine sayıları (frekansı) yaz
            fmt='d',         # Sayıları tam sayı (integer) formatında göster (örn: 5.0 değil 5)
            cmap='YlGnBu',   # Renk paleti (Yellow-Green-Blue: Koyu renkler yüksek frekans)
            linewidths=.5,   # Kutular arasına ince çizgi çek
            cbar_kws={'label': 'Görülme Sıklığı (Frekans)'}) # Renk barı etiketi

plt.title('İlaç Adı ve Yan Etkiler Arasındaki İlişki (2D Dağılım)', fontsize=14, fontweight='bold')
plt.xlabel('Yan Etkiler (Side Effects)', fontsize=12)
plt.ylabel('İlaç Adı (Drug Name)', fontsize=12)

plt.xticks(rotation=45) # Yan etki isimlerini okunur yap
plt.tight_layout()
plt.show()

"""Elde edilen frekans tablosu incelendiğinde, ilaçlar ve yan etkiler arasında rastgele bir dağılım olmadığı, aksine çok belirgin (deterministik) eşleşmeler olduğu görülmektedir:

1. Veri Setindeki En Baskın İlişki: Tablodaki en yüksek frekans değeri 35'tir. Bu değer, Tramadol ilacı ile Mide Bulantısı (Nausea) yan etkisi arasındadır. Bu veri setine göre, bir hastanın yaşayabileceği en muhtemel spesifik durum budur.

2. İlaçların "Birincil" Yan Etkileri: Tablo satır bazında incelendiğinde, her ilacın baskın olarak tek bir yan etkide yoğunlaştığı görülmektedir. En yüksek frekansa sahip diğer eşleşmeler şunlardır:

Amlodipine: En çok Yorgunluk (Fatigue) (29 vaka).

Azithromycin: En çok Baş Ağrısı (Headache) (29 vaka).

Ibuprofen: En çok Mide Ağrısı (Stomach Pain) (29 vaka).

Ciprofloxacin: En çok Baş Dönmesi (Dizziness) (28 vaka).

3. Yan Etkilerin Paylaşımı: Bazı yan etkiler, birden fazla ilacın "en sık görülen" şikayeti olarak karşımıza çıkmaktadır. Yani farklı ilaçlar benzer sonuçlar doğurabilmektedir:

Döküntü (Rash): Hem Amoxicillin (24) hem de Paracetamol (23) kullanan hastalarda en sık görülen şikayettir.

Baş Dönmesi (Dizziness): Hem Ciprofloxacin (28) hem de Metoprolol (20) için birincil yan etkidir.

4. Tablonun %90'ı "0" değerinden oluşmaktadır. Bu durum, ilaçların yan etkilerinin "dağınık" olmadığını gösterir. Örneğin; Amlodipine sütunlarında yüksek bir "Yorgunluk" değeri varken, "Mide Bulantısı" veya "Uykusuzluk" değerleri 0'dır. Bu da veri setindeki ilişkilerin son derece ayırt edici olduğunu kanıtlar.

#5. Bir önceki sorudaki (4. madde) analizde kullandığımız veriler için, seaborn kütüphanesinden clustermap fonksiyonunu kullanarak hiyerarşik kümeleme ve yorumlanması
"""

matris = pd.crosstab(df['Drug_Name'], df['Side_Effects'])

g = sns.clustermap(matris,
                   method='ward',      # Kümeleme yöntemi
                   metric='euclidean', # Uzaklık metriği
                   cmap='viridis',     # Renk paleti
                   figsize=(18, 12),   # Boyut
                   annot=True,         # Sayıları göster
                   fmt='d',            # Sayı formatı (tam sayı)
                   linewidths=.5)      # Hücreler arası çizgi

plt.show()

"""Grafikte her ilaç yalnızca birkaç yan etki sütununda yüksek değer gösteriyor; geri kalan hücreler 0. Bu nedenle kümelenme, esas olarak bu yüksek değerlerin konumuna göre oluşmuş.

Insulin Glargine sadece “Low sugar – Injection site pain – Weight gain” sütunlarında yüksek olduğu için tek bir odak oluşturuyor.

Amoxicillin “Rash – Allergy – Diarrhea” sütunlarında yükseldiği için bu bölgedeki diğer satırlara yaklaşıyor.

Paracetamol, “Rash – Fatigue – Liver issues” hücrelerindeki yüksek değerlerle kendi küçük adacığını oluşturuyor.

Amlodipine ve Metoprolol, ortak “Dizziness” sütununda yüksek oldukları için birbirine yakın kümelenmiş.

Nausea, birçok ilaçta tekrar ettiği için sol taraftaki birçok ilacı birbirine bağlayan ortak bir sütun gibi davranıyor.

Sertraline ve Escitalopram, “uyku/dry mouth/sweating” sütunlarında yükselen değerleri paylaştığı için yan yana geliyor.

Ibuprofen, Tramadol, Metformin gibi ilaçlar “Nausea–GI” bölgesinde yoğunlaştıkları için benzer bir grupta toplanmış.

Genel olarak grafik şunu gösteriyor:
Veri çok seyrek ve her satır birkaç yüksek hücreyle temsil ediliyor. Bu yüzden dendrogram, yüksek değerlerin aynı sütunlarda toplandığı ilaçları aynı kümeye yerleştiriyor.

#6. Yaş (Age) ve Improvement_Score değişkenleri arasındaki korelasyonu hesabı ve yorumlanması
"""

korelasyon = df['Age'].corr(df['Improvement_Score'])

print(f"Yaş (Age) ve İyileşme Skoru (Improvement_Score) Arasındaki Korelasyon: {korelasyon:.4f}")

"""Yaş (Age) ve İyileşme Skoru (Improvement_Score) değişkenleri arasındaki Pearson korelasyon katsayısı = 0.0105 olarak hesaplanmıştır. Bu sonuç ışığında:

İlişki Düzeyi: Katsayının 0'a son derece yakın olması, iki değişken arasında anlamlı bir doğrusal (lineer) ilişki bulunmadığını gösterir.

Yön: Matematiksel olarak pozitif (+) bir değer olsa da, 0.01 düzeyi istatistiksel açıdan ihmal edilebilir bir büyüklüktür. Yani yaşın artması veya azalması, iyileşme skoru üzerinde belirleyici bir etki yaratmamaktadır.

Sonuç: Veri setindeki dağılım incelendiğinde, tedavi başarısının (iyileşme skorunun) yaştan bağımsız olduğu görülmektedir. Modelleme aşamasında yaş değişkeni, iyileşme skorunu açıklayan veya tahmin eden (yordayıcı) bir faktör niteliği taşımamaktadır.

#7. Erkekler ve kadınlar için hastalık (Condition) oranlarını normalize edilmiş bir şekilde hesaplanması. (Her cinsiyet için Toplam:1 )
"""

# Cinsiyet ve Hastalık için Çapraz Tablo (Normalize Edilmiş)
# normalize='index': Satır toplamlarını 1 yapacak şekilde oranlar
cinsiyet_hastalik_oranlari = pd.crosstab(df['Gender'], df['Condition'], normalize='index')

display(cinsiyet_hastalik_oranlari)

"""Analizde, her cinsiyet grubu birim bütün (1.0) kabul edilerek, hastalıkların grup içindeki göreceli oranları hesaplanmıştır. Satır bazlı normalizasyon yapıldığı için her cinsiyetin satır toplamı 1.0'a eşittir.

1. Bulgular ve Yorum:En Yüksek Oranlar (Dominant Durumlar):

Kadınlarda (Female): Kadın hastalarda en büyük pay 0.239 oranıyla Enfeksiyon (Infection) grubuna aittir. Yani yaklaşık olarak her 1000 kadından 239'u enfeksiyon tedavisi görmektedir.

Erkeklerde (Male): Erkek hastalarda ise en yüksek oran 0.222 ile Ağrı Kesici İhtiyacı (Pain Relief) durumudur.

2. Cinsiyete Göre Farklılaşan Oranlar:

Enfeksiyon: Kadınlardaki enfeksiyon oranı (0.239), erkeklerdeki orana (0.193) göre belirgin şekilde daha yüksektir.

Hipertansiyon: Erkeklerde hipertansiyon görülme olasılığı (0.208), kadınlara (0.178) kıyasla daha baskındır.

Benzer (Dengeli) Oranlar:

Depresyon: Her iki cinsiyette de depresyon oranı şaşırtıcı derecede benzerdir (Kadın: 0.176, Erkek: 0.176). Bu durum, cinsiyetin depresyon görülme olasılığı üzerinde ayırt edici bir etkisi olmadığını gösterir.

Diyabet: Kadınlarda $0.214$, erkeklerde $0.201$ ile birbirine yakın oranlar gözlemlenmiştir.

Sonuç: Veri setinde bir kadının enfeksiyon şikayetiyle gelme olasılığı (approx 0.24), bir erkeğin aynı şikayetle gelme olasılığından (approx 0.19) daha yüksektir. Erkeklerde ise ağrı yönetimi ve tansiyon tedavisi, toplam dağılım içinde daha büyük bir yer kaplamaktadır.

#8. Hangi ilaçlar için baş dönmesi (Dizziness) yan etkisi raporlanmıştır? Bu ilaçları azalan sıklığa göre sıralanması
"""

# 1. Adım: Sadece "Dizziness" (Baş Dönmesi) olan satırları filtrele
bas_donmesi_verisi = df[df['Side_Effects'] == 'Dizziness']

# 2. Adım: Hangi ilacın kaç kez geçtiğini say (value_counts otomatik olarak çoktan aza sıralar)
dizziness_siralama = bas_donmesi_verisi['Drug_Name'].value_counts()

# İstersen DataFrame formatında şık bir tablo olarak göster:
dizziness_tablo = dizziness_siralama.to_frame(name='Vaka Sayısı')
dizziness_tablo.index.name = 'İlaç Adı'
display(dizziness_tablo)

"""#9. Metoprolol ilacı için, diğer yan etkilere göre baş dönmesi (Dizziness) yan etkisinin olasılığını hesaplama (Metoprolol için raporlanan tüm yan etkiler içinde Dizziness’in oranı)."""

# 1. Sadece Metoprolol kullananları filtrele
metoprolol_verisi = df[df['Drug_Name'] == 'Metoprolol']

# 2. Toplam Metoprolol vaka sayısı
toplam_vaka = len(metoprolol_verisi)

# 3. İçinde "Dizziness" olanların sayısı
bas_donmesi_sayisi = len(metoprolol_verisi[metoprolol_verisi['Side_Effects'] == 'Dizziness'])

# 4. Olasılığın hesaplanması
olasilik = bas_donmesi_sayisi / toplam_vaka

print(f"Toplam Metoprolol Rapor Sayısı: {toplam_vaka}")
print(f"Baş Dönmesi (Dizziness) Sayısı: {bas_donmesi_sayisi}")
print(f"Olasılık P(Dizziness | Metoprolol): {olasilik:.4f}")
print(f"Yüzdelik Oran: %{olasilik*100:.2f}")